### ISSUE TITLE
(желание) select video quality before start playing

### ISSUE THREAD

**Issue by Kampfader** [TroRg/kodi.kino.pub#12]
hi,
Can someone always make a suggestion before playing the videos, in which quality I would like to play that.

if I see in kodi a new movie / series has only 480p, I do not watch it and wait for a better quality, so you can interact before playing, and stop the Process.

**Comment by quarckster** [comment]
@Kampfader your RFE has been implemented.

**Comment by Kampfader** [comment]
Спасибо большое, сейчас только осталась функция библиотеки для фильмов и сериал   :)
