### ISSUE TITLE
Build addon

### ISSUE THREAD

**Issue by Kampfader** [TroRg/kodi.kino.pub#15]
Hi,
How can i build this addon for install from .zip on kodi 17?

**Comment by quarckster** [comment]
just download this repo as a zip file

**Comment by Kampfader** [comment]
i can not install this .zip (kodi.kino.pub-master.zip) on kodi krypton..
im rename this to kodi.kino.pub.zip is the same problem.

**Comment by Kampfader** [comment]
i install first the original addon from the kino.pub site, then download the .master.zip from here and replace the addon files, the addon does not start then, no matter if kodi 17 or 18

**Comment by Kampfader** [comment]
Can u install the master.zip?

@Quarckster

**Comment by quarckster** [comment]
Sorry fore delay. Yeah there is a problem. In order to install the plugin you need to download the repo, unpack master.zip, then you need to make a zip archive from `video.kino.pub` folder.

**Comment by Kampfader** [comment]
that is, thanks u..
