### ISSUE TITLE
It is not possible to go to the next pages in the bookmarks. / В закладках невозможно перейти на следующие страницы.

### ISSUE THREAD

**Issue by olsamurai** [TroRg/kodi.kino.pub#32]
The first page in any section of the "Bookmarks" is displayed correctly. When trying to go to the next page, it will report an error in addon. Most likely, it's because the secret token of session is missing in the GET-Request. (In version 1.2.1, the token is sent in the request)

Первая страница в любом разделе "Закладки" отображается корректно. Попытка перехода на следующие страницы вызывает ошибку. Вероятно связано с тем, что в GET-запросе нет сессионного секретного токена. (В версии 1.2.1 токен передается в запросе)

**Comment by relictMarauder** [comment]
Мой вариант решения проблемы: pull-request #33

**Comment by quarckster** [comment]
отправьте этот issue в репозиторий https://github.com/quarckster/kodi.kino.pub
